# Generated by Django 3.0 on 2020-01-26 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='N', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EpyphyticOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=256)),
                ('longhitude', models.CharField(max_length=256)),
                ('dbh', models.DecimalField(decimal_places=2, max_digits=19)),
                ('collection_date', models.DateField(default=datetime.datetime(2020, 1, 26, 7, 1, 18, 801256, tzinfo=utc))),
                ('host_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Tree')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenEpyphyticOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Direction')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.EpyphyticOrganism')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bark_texture', models.CharField(choices=[('s', 'smooth'), ('r', 'rough')], default='s', max_length=8)),
                ('stain', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Direction')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=19)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Direction')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
    ]
