# Generated by Django 3.0 on 2020-04-19 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('code', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.CharField(blank=True, default='', max_length=256)),
                ('longhitude', models.CharField(blank=True, default='', max_length=256)),
                ('dbh', models.DecimalField(decimal_places=2, max_digits=19)),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('host_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Tree')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
    ]
