# Generated by Django 3.0 on 2020-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0002_auto_20200209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='code',
            field=models.CharField(blank=True, default='<Blank>', max_length=128),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='latitude',
            field=models.CharField(blank=True, default='Not Specified', max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='longhitude',
            field=models.CharField(blank=True, default='Not Specified', max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='name',
            field=models.CharField(blank=True, default='<Blank>', max_length=256),
        ),
    ]
