# Generated by Django 3.0 on 2020-02-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0003_auto_20200209_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='EastDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='N', max_length=8)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.EastDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='N', max_length=8)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.NorthDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='N', max_length=8)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.SouthDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='N', max_length=8)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.WestDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='specimendetails',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='specimenepyphyticorganism',
            name='direction',
        ),
        migrations.AddField(
            model_name='specimenepyphyticorganism',
            name='specimen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specimen',
            name='code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='longhitude',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='specimendetails',
            name='specimen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='westdetails',
            name='specimen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
        migrations.AddField(
            model_name='southdetails',
            name='specimen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
        migrations.AddField(
            model_name='northdetails',
            name='specimen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
        migrations.AddField(
            model_name='eastdetails',
            name='specimen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen'),
        ),
    ]
