# Generated by Django 3.0 on 2020-02-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0005_auto_20200216_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eastdetails',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='northdetails',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='southdetails',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='westdetails',
            name='direction',
        ),
    ]
