# Generated by Django 3.0 on 2020-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0006_auto_20200216_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='bark_texture',
            field=models.CharField(choices=[('s', 'smooth'), ('r', 'rough')], default='s', max_length=8),
        ),
        migrations.AddField(
            model_name='specimen',
            name='stain',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='SpecimenDetails',
        ),
    ]
