# Generated by Django 3.0 on 2020-02-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0007_auto_20200216_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='state_of_decay',
            field=models.CharField(choices=[('i', 'intact'), ('mi', 'moderately intact'), ('l', 'loose')], default='i', max_length=8),
        ),
    ]
