# Generated by Django 3.0 on 2020-04-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0009_auto_20200223_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='bark_texture',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='stain',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='state_of_decay',
        ),
    ]
