# Generated by Django 3.0 on 2020-04-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('specimen', '0010_auto_20200405_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
