# Generated by Django 3.0 on 2020-04-19 11:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specimen', '0001_initial'),
        ('epiphytes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WestOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='specimen_images/west/')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level_1', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_2', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_3', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('state_of_decay', models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8)),
                ('bark_texture', models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8)),
                ('stain', models.BooleanField(default=True)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specimen_images/south/')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level_1', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_2', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_3', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('state_of_decay', models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8)),
                ('bark_texture', models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8)),
                ('stain', models.BooleanField(default=True)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specimen_images/north/')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level_1', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_2', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_3', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('state_of_decay', models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8)),
                ('bark_texture', models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8)),
                ('stain', models.BooleanField(default=True)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specimen_images/east/')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level_1', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_2', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ph_level_3', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('state_of_decay', models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8)),
                ('bark_texture', models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8)),
                ('stain', models.BooleanField(default=True)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
