# Generated by Django 3.0 on 2020-02-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specimen', '0009_auto_20200223_1531'),
        ('epiphytes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WestOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SouthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NorthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiphytic_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiphytes.EpiphyticOrganism')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EastDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=19)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.Specimen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
