# Generated by Django 3.0 on 2020-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_auto_20200223_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eastimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direction_images/'),
        ),
        migrations.AlterField(
            model_name='northimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direction_images/'),
        ),
        migrations.AlterField(
            model_name='southimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direction_images/'),
        ),
        migrations.AlterField(
            model_name='westimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direction_images/'),
        ),
    ]
