# Generated by Django 3.0 on 2020-03-01 03:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_auto_20200225_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eastimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='specimen_images/east/'),
        ),
        migrations.AlterField(
            model_name='northimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='specimen_images/north/'),
        ),
        migrations.AlterField(
            model_name='southimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='specimen_images/south/'),
        ),
        migrations.AlterField(
            model_name='westimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='specimen_images/west/'),
        ),
    ]
