# Generated by Django 3.0 on 2020-04-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0007_auto_20200301_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='eastdetails',
            name='bark_texture',
            field=models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8),
        ),
        migrations.AddField(
            model_name='eastdetails',
            name='stain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eastdetails',
            name='state_of_decay',
            field=models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8),
        ),
        migrations.AddField(
            model_name='northdetails',
            name='bark_texture',
            field=models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8),
        ),
        migrations.AddField(
            model_name='northdetails',
            name='stain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='northdetails',
            name='state_of_decay',
            field=models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8),
        ),
        migrations.AddField(
            model_name='southdetails',
            name='bark_texture',
            field=models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8),
        ),
        migrations.AddField(
            model_name='southdetails',
            name='stain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='southdetails',
            name='state_of_decay',
            field=models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8),
        ),
        migrations.AddField(
            model_name='westdetails',
            name='bark_texture',
            field=models.CharField(choices=[('s', 'Smooth'), ('r', 'Rough')], default='s', max_length=8),
        ),
        migrations.AddField(
            model_name='westdetails',
            name='stain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='westdetails',
            name='state_of_decay',
            field=models.CharField(choices=[('i', 'Intact'), ('mi', 'Moderately Intact'), ('l', 'Loose')], default='i', max_length=8),
        ),
    ]
